name: flutter_application
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
    sdk: ">=3.1.3 <4.0.0"

dependencies:
    flutter:
        sdk: flutter
    scroll_date_picker: "3.7.3"
    file_picker: ^4.0.10
    dio: ^4.0.0
    video_player: ^2.8.1
    video_thumbnail: ^0.5.3
    path_provider: ^2.0.5
    cupertino_icons: ^1.0.6
    http: ^1.1.0
    shared_preferences: ^2.2.1
    flutter_dotenv: ^5.1.0
    firebase_core: ^2.21.0
    firebase_messaging: ^14.7.3
    font_awesome_flutter: ^10.6.0
    intl: ^0.17.0
    url_launcher: ^6.0.9
    image_picker: ^1.0.4
    http_parser: ^4.0.2
    cached_network_image: ^3.3.0
    visibility_detector: ^0.4.0+2
    flutter_reaction_button: ^3.0.0+3
dev_dependencies:
    flutter_test:
        sdk: flutter
    webview_flutter:
    flutter_lints: ^2.0.0

flutter:
    uses-material-design: true
    assets:
        - assets/
        - assets/chinhsach.html
        - assets/img/nav/
        - assets/img/reaction/
        - assets/img/icon/
        - assets/img/bar/
        - assets/images/menu/
        - assets/img/notification/
    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware

    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/assets-and-images/#from-packages

    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
    # fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    #
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/custom-fonts/#from-packages
